spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: task_db_admin
    password: qwe123QWE!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false

server:
  port: 8080
  servlet:
    session:
      timeout: 10m

